import { TemplateGroup, UAResult } from '../workers/NetTraffic.worker';

export type DiffStatus = 'NEW' | 'REMOVED' | 'INCREASED' | 'DECREASED' | 'UNCHANGED';

export interface EndpointDiff {
  templateUri: string;
  leftCount: number;
  rightCount: number;
  diff: number;
  diffPercent: number; // Infinity if leftCount is 0
  status: DiffStatus;
  leftVariations: number;
  rightVariations: number;
}

export interface UADiff {
  fingerprint: string;
  leftCount: number;
  rightCount: number;
  diff: number;
  status: DiffStatus;
  clientName: string;
  version: string;
}

export function compareEndpoints(left: TemplateGroup[], right: TemplateGroup[]): EndpointDiff[] {
  const map = new Map<string, EndpointDiff>();

  // Use a heuristic for matching templateUri 
  // left/right templateUri are essentially the same if generated by the same patterns.
  left.forEach(l => {
    map.set(l.templateUri, {
      templateUri: l.templateUri,
      leftCount: l.totalCount,
      rightCount: 0,
      diff: -l.totalCount,
      diffPercent: -100,
      status: 'REMOVED',
      leftVariations: l.rawCalls.length,
      rightVariations: 0,
    });
  });

  right.forEach(r => {
    const existing = map.get(r.templateUri);
    if (existing) {
      existing.rightCount = r.totalCount;
      existing.diff = r.totalCount - existing.leftCount;
      existing.rightVariations = r.rawCalls.length;
      if (existing.diff > 0) existing.status = 'INCREASED';
      else if (existing.diff < 0) existing.status = 'DECREASED';
      else existing.status = 'UNCHANGED';
      
      existing.diffPercent = existing.leftCount > 0 
        ? (existing.diff / existing.leftCount) * 100 
        : Infinity;
    } else {
      map.set(r.templateUri, {
        templateUri: r.templateUri,
        leftCount: 0,
        rightCount: r.totalCount,
        diff: r.totalCount,
        diffPercent: Infinity,
        status: 'NEW',
        leftVariations: 0,
        rightVariations: r.rawCalls.length,
      });
    }
  });

  // Sort by largest absolute diff first, to highlight spikes and drops
  return Array.from(map.values()).sort((a, b) => Math.abs(b.diff) - Math.abs(a.diff));
}

export function compareUAs(left: UAResult[], right: UAResult[]): UADiff[] {
  const map = new Map<string, UADiff>();

  const getKey = (vars: Record<string, string>) => JSON.stringify(vars);

  left.forEach(l => {
    const key = getKey(l.variables);
    map.set(key, {
      fingerprint: key,
      clientName: l.variables?.ClientName || Object.values(l.variables)[0] || 'Unknown',
      version: l.variables?.Version || l.variables?.ClientVersion || 'Unknown',
      leftCount: l.count,
      rightCount: 0,
      diff: -l.count,
      status: 'REMOVED',
    });
  });

  right.forEach(r => {
    const key = getKey(r.variables);
    const existing = map.get(key);
    if (existing) {
      existing.rightCount = r.count;
      existing.diff = r.count - existing.leftCount;
      if (existing.diff > 0) existing.status = 'INCREASED';
      else if (existing.diff < 0) existing.status = 'DECREASED';
      else existing.status = 'UNCHANGED';
    } else {
      map.set(key, {
        fingerprint: key,
        clientName: r.variables?.ClientName || Object.values(r.variables)[0] || 'Unknown',
        version: r.variables?.Version || r.variables?.ClientVersion || 'Unknown',
        leftCount: 0,
        rightCount: r.count,
        diff: r.count,
        status: 'NEW',
      });
    }
  });

  return Array.from(map.values()).sort((a, b) => Math.abs(b.diff) - Math.abs(a.diff));
}
